schema_version: 20180708
name: ontology
version: 0.0.26
runtime: java11
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.124
run_image: fnproject/fn-java-fdk:jre11-1.0.124
cmd: com.indra.onesait.webapp.net.PingServiceApplication::main
config:
  GRAYLOG_HOST: log-centralizer
  GRAYLOG_PORT: "12201"
triggers:
  - name: endpoint
    type: http
    source: /net-ping